"""empty message

Revision ID: c3dca661c1fa
Revises: bf6a38379cbf
Create Date: 2023-07-26 15:08:11.221686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3dca661c1fa'
down_revision = 'bf6a38379cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('lesson_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint('bookings_member_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookings_lesson_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['id'])
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['id'])
        batch_op.drop_column('lesson')
        batch_op.drop_column('member')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lesson', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookings_lesson_fkey', 'lessons', ['lesson'], ['id'])
        batch_op.create_foreign_key('bookings_member_fkey', 'members', ['member'], ['id'])
        batch_op.drop_column('lesson_id')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
